import type { Channel, Notification, SheetRow, User } from "./types";

export const MOCK_CHANNELS: Channel[] = [
  {
    id: "ca-news-1",
    name: "Orvion News HQ",
    platform: "YouTube",
    status: "Active",
    manager: "Rahul Sharma",
    team: ["Aisha K.", "Ben L.", "Carla R."],
    mode: "Manual",
    apiConnected: false,
    todayCount: 4,
    pendingSheets: 2,
    kpiStatus: "On Track",
    lastUpdated: "2 min ago",
  },
  {
    id: "ca-news-2",
    name: "Orvion World",
    platform: "YouTube",
    status: "Active",
    manager: "Priya Mehta",
    team: ["David S.", "Emma W."],
    mode: "API",
    apiConnected: true,
    todayCount: 2,
    pendingSheets: 1,
    kpiStatus: "At Risk",
    lastUpdated: "15 min ago",
  },
];

const baseRow = (overrides: Partial<SheetRow> & { id: string }): SheetRow =>
  ({ ...overrides }) as SheetRow;

export const MOCK_SHEET_DATA: Record<string, SheetRow[]> = {
  "content-monitoring": [
    baseRow({
      id: "cm1",
      date: "2026-06-12",
      channel: "Orvion News HQ",
      topic: "Election Recap",
      video: "Top stories — June 12",
      views: 28450,
      likes: 1820,
      comments: 312,
      ctr: "6.2%",
      watchTime: "4:32",
      subChange: 184,
      performance: "Good",
      issue: "—",
      action: "Monitor",
      analyst: "Carla R.",
      notes: "Trending in IN",
    }),
    baseRow({
      id: "cm2",
      date: "2026-06-12",
      channel: "Orvion World",
      topic: "G20 Summit",
      video: "Live coverage cut",
      views: 9120,
      likes: 540,
      comments: 88,
      ctr: "3.1%",
      watchTime: "2:10",
      subChange: 22,
      performance: "Average",
      issue: "Low CTR",
      action: "New thumbnail",
      analyst: "Emma W.",
      notes: "",
    }),
  ],
  "daily-content": [
    baseRow({
      id: "dc1",
      date: "2026-06-13",
      topic: "Markets close",
      channel: "Orvion News HQ",
      type: "Short",
      writer: "Aisha K.",
      editor: "Ben L.",
      priority: "High",
      script: "Done",
      voice: "In Progress",
      editing: "Pending",
      thumbnail: "Pending",
      upload: "Pending",
      deadline: "2026-06-13",
      notes: "",
    }),
    baseRow({
      id: "dc2",
      date: "2026-06-13",
      topic: "Weather alert",
      channel: "Orvion News HQ",
      type: "Long form",
      writer: "Carla R.",
      editor: "Ben L.",
      priority: "Medium",
      script: "In Progress",
      voice: "Pending",
      editing: "Pending",
      thumbnail: "Pending",
      upload: "Pending",
      deadline: "2026-06-14",
      notes: "Need stock footage",
    }),
  ],
  "edit-plans": [
    baseRow({
      id: "ep1",
      title: "Markets close — June 13",
      channel: "Orvion News HQ",
      editor: "Ben L.",
      raw: "Received",
      voice: "Recorded",
      graphics: "In Progress",
      thumb: "Pending",
      timeline: "In Progress",
      review: "Pending",
      revisions: 0,
      render: "Pending",
      deadline: "2026-06-13",
      notes: "",
    }),
  ],
  fpc: [
    baseRow({
      id: "fpc1",
      date: "2026-06-13",
      channel: "Orvion News HQ",
      item: "Markets close package",
      file: "Uploaded",
      production: "In Progress",
      check: "Pending",
      person: "Aisha K.",
      priority: "High",
      deadline: "2026-06-13",
      approval: "Pending",
      notes: "",
    }),
  ],
  kpi: [
    baseRow({
      id: "kpi1",
      channel: "Orvion News HQ",
      dailyTarget: 4,
      weeklyTarget: 28,
      monthlyTarget: 120,
      viewsTarget: 2000000,
      watchTarget: "120k hrs",
      subTarget: 25000,
      ctrTarget: "6%",
      productivity: "85%",
      progress: "78%",
      performance: "On Track",
      notes: "",
    }),
    baseRow({
      id: "kpi2",
      channel: "Orvion World",
      dailyTarget: 2,
      weeklyTarget: 14,
      monthlyTarget: 60,
      viewsTarget: 800000,
      watchTarget: "60k hrs",
      subTarget: 10000,
      ctrTarget: "5%",
      productivity: "70%",
      progress: "62%",
      performance: "At Risk",
      notes: "",
    }),
  ],
};

export const MOCK_NOTIFICATIONS: Notification[] = [
  { id: "n1", type: "Sheet", title: "Daily Content updated", description: "Aisha K. updated 3 rows", project: "News", read: false, createdAt: "5m" },
  { id: "n2", type: "Task", title: "Task assigned to you", description: "Edit: Markets close — June 13", project: "News", read: false, createdAt: "12m" },
  { id: "n3", type: "KPI", title: "KPI missed", description: "Orvion World below CTR target", project: "News", read: false, createdAt: "1h" },
  { id: "n4", type: "Approval", title: "Approval needed", description: "Thumbnail v3 awaiting approval", project: "News", read: true, createdAt: "2h" },
  { id: "n5", type: "Editing", title: "Editing task completed", description: "Render finished for G20 cut", project: "News", read: true, createdAt: "3h" },
  { id: "n6", type: "RDP", title: "RDP disconnected", description: "Edit-Station-02 lost connection", project: "News", read: false, createdAt: "4h" },
  { id: "n7", type: "API", title: "API connection issue", description: "YouTube API quota near limit", project: "News", read: false, createdAt: "6h" },
  { id: "n8", type: "Comment", title: "New comment", description: "Priya: 'Let's reshoot the intro'", project: "News", read: true, createdAt: "8h" },
  { id: "n9", type: "Project", title: "New project added", description: "News project created", read: true, createdAt: "1d" },
  { id: "n10", type: "Permission", title: "Permission changed", description: "Ben L. promoted to Editor", read: true, createdAt: "2d" },
];

export const MOCK_USERS: User[] = [
  { id: "u1", name: "Rahul Sharma", email: "rahul@orvion.media", role: "Project Manager", projects: ["News"], channels: ["Orvion News HQ"], sheets: ["all"], status: "Active", lastLogin: "Today 09:14" },
  { id: "u2", name: "Priya Mehta", email: "priya@orvion.media", role: "Project Manager", projects: ["News"], channels: ["Orvion World"], sheets: ["all"], status: "Active", lastLogin: "Today 08:42" },
  { id: "u3", name: "Aisha Khan", email: "aisha@orvion.media", role: "Content Manager", projects: ["News"], channels: ["Orvion News HQ"], sheets: ["Daily Content", "FPC"], status: "Active", lastLogin: "Today 10:01" },
  { id: "u4", name: "Ben Lawson", email: "ben@orvion.media", role: "Editor", projects: ["News"], channels: ["Orvion News HQ"], sheets: ["Edit Plans"], status: "Active", lastLogin: "Today 07:50" },
  { id: "u5", name: "Carla Rivera", email: "carla@orvion.media", role: "Analyst", projects: ["News"], channels: ["Orvion News HQ"], sheets: ["Content Monitoring", "KPI"], status: "Active", lastLogin: "Yesterday 18:30" },
  { id: "u6", name: "Devon Park", email: "devon@orvion.media", role: "HR", projects: [], channels: [], sheets: [], status: "Active", lastLogin: "Today 09:00" },
  { id: "u7", name: "Maya Chen", email: "maya@orvion.media", role: "Finance", projects: [], channels: [], sheets: [], status: "Active", lastLogin: "Today 08:55" },
  { id: "u8", name: "Omar Idris", email: "omar@orvion.media", role: "IT", projects: ["News"], channels: ["all"], sheets: ["all"], status: "Active", lastLogin: "Today 09:20" },
];

export const MOCK_ANALYTICS = {
  views: Array.from({ length: 14 }, (_, i) => ({ day: `D${i + 1}`, value: 8000 + Math.round(Math.random() * 6000) })),
  subs: Array.from({ length: 14 }, (_, i) => ({ day: `D${i + 1}`, value: 50 + Math.round(Math.random() * 200) })),
  watch: Array.from({ length: 14 }, (_, i) => ({ day: `D${i + 1}`, value: 1200 + Math.round(Math.random() * 800) })),
  engagement: Array.from({ length: 14 }, (_, i) => ({ day: `D${i + 1}`, likes: 200 + Math.round(Math.random() * 400), comments: 30 + Math.round(Math.random() * 80) })),
};

export const MOCK_EMPLOYEES = [
  { id: "e1", name: "Rahul Sharma", dept: "Content", role: "Project Manager", email: "rahul@orvion.media", joined: "2024-02-10", status: "Active" },
  { id: "e2", name: "Priya Mehta", dept: "Content", role: "Project Manager", email: "priya@orvion.media", joined: "2024-03-22", status: "Active" },
  { id: "e3", name: "Aisha Khan", dept: "Editorial", role: "Content Manager", email: "aisha@orvion.media", joined: "2024-05-01", status: "Active" },
  { id: "e4", name: "Ben Lawson", dept: "Post-Production", role: "Editor", email: "ben@orvion.media", joined: "2024-06-12", status: "Active" },
  { id: "e5", name: "Carla Rivera", dept: "Analytics", role: "Analyst", email: "carla@orvion.media", joined: "2024-08-19", status: "Active" },
  { id: "e6", name: "Devon Park", dept: "HR", role: "HR Manager", email: "devon@orvion.media", joined: "2024-01-04", status: "Active" },
  { id: "e7", name: "Maya Chen", dept: "Finance", role: "Finance Lead", email: "maya@orvion.media", joined: "2024-01-10", status: "Active" },
  { id: "e8", name: "Omar Idris", dept: "IT", role: "IT Lead", email: "omar@orvion.media", joined: "2024-01-15", status: "Active" },
];

export const MOCK_SALARIES = MOCK_EMPLOYEES.map((e, i) => ({
  id: `s${i + 1}`,
  employee: e.name,
  role: e.role,
  base: 60000 + i * 4500,
  bonus: 2000 + i * 250,
  status: i % 4 === 0 ? "Pending" : "Paid",
}));

export const MOCK_TICKETS = [
  { id: "t1", title: "Cannot open Edit Plans sheet", priority: "High", status: "Open", assignee: "Omar Idris", created: "2026-06-12" },
  { id: "t2", title: "RDP latency on Edit-Station-02", priority: "Medium", status: "In Progress", assignee: "Omar Idris", created: "2026-06-11" },
  { id: "t3", title: "YouTube API quota alert", priority: "High", status: "In Progress", assignee: "Omar Idris", created: "2026-06-13" },
  { id: "t4", title: "Add new analyst to channel", priority: "Low", status: "Closed", assignee: "Omar Idris", created: "2026-06-09" },
];