import type { SheetDef } from "./types";

export const SHEET_DEFS: SheetDef[] = [
  {
    key: "content-monitoring",
    name: "Content Monitoring",
    description: "Track published content performance.",
    columns: [
      { key: "date", label: "Date", type: "date" },
      { key: "channel", label: "Channel" },
      { key: "topic", label: "Topic" },
      { key: "video", label: "Published Video" },
      { key: "views", label: "Views", type: "number" },
      { key: "likes", label: "Likes", type: "number" },
      { key: "comments", label: "Comments", type: "number" },
      { key: "ctr", label: "CTR" },
      { key: "watchTime", label: "Watch Time" },
      { key: "subChange", label: "Sub. Change", type: "number" },
      { key: "performance", label: "Performance", type: "status", options: ["Good", "Average", "Poor"] },
      { key: "issue", label: "Issue Found" },
      { key: "action", label: "Action Needed" },
      { key: "analyst", label: "Analyst", type: "user" },
      { key: "notes", label: "Notes" },
    ],
  },
  {
    key: "daily-content",
    name: "Daily Content",
    description: "Daily production plan across the team.",
    columns: [
      { key: "date", label: "Date", type: "date" },
      { key: "topic", label: "Topic" },
      { key: "channel", label: "Channel" },
      { key: "type", label: "Type" },
      { key: "writer", label: "Writer", type: "user" },
      { key: "editor", label: "Editor", type: "user" },
      { key: "priority", label: "Priority", type: "status", options: ["High", "Medium", "Low"] },
      { key: "script", label: "Script", type: "status", options: ["Pending", "In Progress", "Done"] },
      { key: "voice", label: "Voice", type: "status", options: ["Pending", "In Progress", "Done"] },
      { key: "editing", label: "Editing", type: "status", options: ["Pending", "In Progress", "Done"] },
      { key: "thumbnail", label: "Thumbnail", type: "status", options: ["Pending", "In Progress", "Done"] },
      { key: "upload", label: "Upload", type: "status", options: ["Pending", "Scheduled", "Live"] },
      { key: "deadline", label: "Deadline", type: "date" },
      { key: "notes", label: "Notes" },
    ],
  },
  {
    key: "edit-plans",
    name: "Edit Plans",
    description: "Editing pipeline status.",
    columns: [
      { key: "title", label: "Video Title" },
      { key: "channel", label: "Channel" },
      { key: "editor", label: "Editor", type: "user" },
      { key: "raw", label: "Raw Footage", type: "status", options: ["Pending", "Received", "Approved"] },
      { key: "voice", label: "Voiceover", type: "status", options: ["Pending", "Recorded", "Approved"] },
      { key: "graphics", label: "Graphics", type: "status", options: ["Pending", "In Progress", "Done"] },
      { key: "thumb", label: "Thumbnail", type: "status", options: ["Pending", "In Progress", "Done"] },
      { key: "timeline", label: "Timeline", type: "status", options: ["Pending", "In Progress", "Done"] },
      { key: "review", label: "Review", type: "status", options: ["Pending", "In Review", "Approved"] },
      { key: "revisions", label: "Revisions", type: "number" },
      { key: "render", label: "Final Render", type: "status", options: ["Pending", "Rendering", "Done"] },
      { key: "deadline", label: "Deadline", type: "date" },
      { key: "notes", label: "Notes" },
    ],
  },
  {
    key: "fpc",
    name: "FPC",
    description: "File / Production / Check tracking.",
    columns: [
      { key: "date", label: "Date", type: "date" },
      { key: "channel", label: "Channel" },
      { key: "item", label: "Content Item" },
      { key: "file", label: "File", type: "status", options: ["Missing", "Uploaded", "Verified"] },
      { key: "production", label: "Production", type: "status", options: ["Pending", "In Progress", "Done"] },
      { key: "check", label: "Check", type: "status", options: ["Pending", "Passed", "Failed"] },
      { key: "person", label: "Assigned", type: "user" },
      { key: "priority", label: "Priority", type: "status", options: ["High", "Medium", "Low"] },
      { key: "deadline", label: "Deadline", type: "date" },
      { key: "approval", label: "Approval", type: "status", options: ["Pending", "Approved", "Rejected"] },
      { key: "notes", label: "Notes" },
    ],
  },
  {
    key: "kpi",
    name: "KPI",
    description: "Channel performance targets and progress.",
    columns: [
      { key: "channel", label: "Channel" },
      { key: "dailyTarget", label: "Daily Videos", type: "number" },
      { key: "weeklyTarget", label: "Weekly Videos", type: "number" },
      { key: "monthlyTarget", label: "Monthly Uploads", type: "number" },
      { key: "viewsTarget", label: "Views Target", type: "number" },
      { key: "watchTarget", label: "Watch Time Target" },
      { key: "subTarget", label: "Subscribers Target", type: "number" },
      { key: "ctrTarget", label: "CTR Target" },
      { key: "productivity", label: "Team Productivity" },
      { key: "progress", label: "Actual Progress" },
      { key: "performance", label: "Status", type: "status", options: ["On Track", "At Risk", "Off Track"] },
      { key: "notes", label: "Notes" },
    ],
  },
];

export function getSheetDef(key: string) {
  return SHEET_DEFS.find((s) => s.key === key);
}